version: '3.7'
services:
  mongodb:
    image: mongo:4.2.0
    ports:
      - 27017:27017
  geolocation:
    build: ./
    links:
      - mongodb
    ports:
      - 8080:8080
    environment:
      MICRONAUT_SERVER_HOST: geolocation
      MICRONAUT_SERVER_PORT: 8080
      MONGO_HOST: mongodb
      MONGO_PORT: 27017

