mongodb.uri: mongodb://${MONGO_HOST:localhost}:${MONGO_PORT:27017}

micronaut:
  application.name: geolocation
  server.port: -1

geolocation:
  database: geolocation
  coordinatesCollection: coordinates
